<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-10-15T17:41:00 IST" name="Suite" finished-at="2023-10-15T17:41:02 IST" duration-ms="1505">
    <groups>
    </groups>
    <test started-at="2023-10-15T17:41:00 IST" name="Test" finished-at="2023-10-15T17:41:02 IST" duration-ms="1505">
      <class name="com.qa.testscripts.saucedemo_SeleniumJava">
        <test-method is-config="true" signature="startURL()[pri:0, instance:com.qa.testscripts.saucedemo_SeleniumJava@73e9cf30]" started-at="2023-10-15T17:40:54 IST" name="startURL" finished-at="2023-10-15T17:41:00 IST" duration-ms="6256" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startURL -->
        <test-method signature="validate_title()[pri:0, instance:com.qa.testscripts.saucedemo_SeleniumJava@73e9cf30]" started-at="2023-10-15T17:41:00 IST" name="validate_title" finished-at="2023-10-15T17:41:00 IST" duration-ms="21" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Swag Labs expected [Swag Labs] but found [sauce demo login page launched]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Swag Labs expected [Swag Labs] but found [sauce demo login page launched]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at com.qa.testscripts.saucedemo_SeleniumJava.validate_title(saucedemo_SeleniumJava.java:56)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validate_title -->
        <test-method signature="loginwithvalid(java.lang.String,java.lang.String)[pri:1, instance:com.qa.testscripts.saucedemo_SeleniumJava@73e9cf30]" started-at="2023-10-15T17:41:00 IST" name="loginwithvalid" finished-at="2023-10-15T17:41:01 IST" duration-ms="990" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[standard_user]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[secret_sauce]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginwithvalid -->
        <test-method signature="loginwithinvalid(java.lang.String,java.lang.String)[pri:2, instance:com.qa.testscripts.saucedemo_SeleniumJava@73e9cf30]" started-at="2023-10-15T17:41:01 IST" name="loginwithinvalid" finished-at="2023-10-15T17:41:02 IST" duration-ms="424" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[standard_Invaliduser]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[secret_Invalidpwd]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginwithinvalid -->
        <test-method is-config="true" signature="closewindow()[pri:0, instance:com.qa.testscripts.saucedemo_SeleniumJava@73e9cf30]" started-at="2023-10-15T17:41:02 IST" name="closewindow" finished-at="2023-10-15T17:41:02 IST" duration-ms="198" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closewindow -->
      </class> <!-- com.qa.testscripts.saucedemo_SeleniumJava -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
